[package]
name = "style4rs-util"
version = "0.1.0"
edition = "2021"

[dependencies]
lightningcss = { version = "1.0.0-alpha.51", features = ["serde", "visitor"] }
proc-macro2 = { version = "*", features = ["proc-macro"] }
quote = "*"
regex = "*"
selectors = "*"
