[package]
name = "style4rs"
version = "0.1.0"
description = "Scoped CSS for Rust web frameworks like Leptos"
licence = "MIT"
repository = "https://github.com/nigeleke/style4rs"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = { version = "1.0.69", features = ["proc-macro", "span-locations"] }
quote = "1.0.33"
style4rs-util = { path = "../style4rs-util", version = "0.1.0" }
syn = { version = "2.0.39", features = ["full", "visit"] }
