[package]
name = "style4rs-test"
version.workspace = true
edition.workspace = true

[dependencies]
style4rs = { path = "../style4rs" }

[build-dependencies]
style4rs-builder = { path = "../style4rs-builder" }
