# Run acceptance-cycle on develop commits.
#
# Acceptance cycle comprises:
# - run tests on develop
# - release into main with bumped versions
#
name: Acceptance Cycle

on:
  push:
    branches:
      - develop

jobs:
  acceptance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: License Header Check
      #   run: sbt headerCheck

      - name: Test
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --out xml

      - name: Publish to Codecov
        uses: codecov/codecov-action@v3

      - name: Documentation
        run: cargo doc

  release:
    needs: acceptance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # TODO: Bump version using cargo-release ???
      - name: Build
        run: |
          git config --global user.email "nigeleke@users.noreply.github.com"
          git config --global user.name "Nigel Eke"
          export VERSION=$(cargo metadata --format-version 1 --no-deps | grep -A 2 '"name":"style4rs"' | grep '"version"' | awk '{print $2}' | tr -d '",')
          git tag $VERSION
          git checkout main
          git merge $VERSION
          git push

# cargo install cargo-release
# cargo release --help
# cargo release --package style4rs --no-verify
