# Run publish-cycle on main commits.
#
# Publish cycle comprises:
# - publish site, coverage reports and API documentation to https://nigeleke.github.io
#
name: Publish Cycle

on:
  workflow_run:
    workflows: ["Acceptance Cycle"]
    branches: [develop]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run: |
          cargo doc --package style4rs --no-deps
          cargo install cargo-tarpaulin
          cargo tarpaulin --out html --output-dir target/doc --jobs 1
          mkdir docs0
          mkdir -p docs0/core
          mkdir -p docs0/coverage
          cp README.md docs0/
          cp -R target/doc/style4rs/* docs0/core
          cp -R target/doc/tarpaulin-report.html docs0/coverage/index.html
          cargo tarpaulin --out xml --jobs 1

      - name: Publish to Codecov
        uses: codecov/codecov-action@v3

      - name: Publish
        run: |
          git config --global user.email "nigeleke@users.noreply.github.com"
          git config --global user.name "Nigel Eke"
          export VERSION=$(git describe --abbrev=0 --tags)
          git checkout gh-pages
          rm -rf docs
          mv docs0 docs
          git add .
          git commit -m "Release $VERSION"
          git push
